// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZctOnLjQ7rw7BAmjKI_u8_wiJWpaHvfQ',
    appId: '1:772536368309:web:29844ce05a2f12f9f192fc',
    messagingSenderId: '772536368309',
    projectId: 'real-estate-app-482d8',
    authDomain: 'real-estate-app-482d8.firebaseapp.com',
    storageBucket: 'real-estate-app-482d8.firebasestorage.app',
    measurementId: 'G-79C85HX6WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlb5_h7Cctj86BKh2bMFW2XRWcl5-npr8',
    appId: '1:772536368309:android:0639b0322588e984f192fc',
    messagingSenderId: '772536368309',
    projectId: 'real-estate-app-482d8',
    storageBucket: 'real-estate-app-482d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS60GEu6CfAHBTG_Ciq8tKDjQnVWrVQeI',
    appId: '1:772536368309:ios:96a860da543187f9f192fc',
    messagingSenderId: '772536368309',
    projectId: 'real-estate-app-482d8',
    storageBucket: 'real-estate-app-482d8.firebasestorage.app',
    iosBundleId: 'com.example.estateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS60GEu6CfAHBTG_Ciq8tKDjQnVWrVQeI',
    appId: '1:772536368309:ios:96a860da543187f9f192fc',
    messagingSenderId: '772536368309',
    projectId: 'real-estate-app-482d8',
    storageBucket: 'real-estate-app-482d8.firebasestorage.app',
    iosBundleId: 'com.example.estateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZctOnLjQ7rw7BAmjKI_u8_wiJWpaHvfQ',
    appId: '1:772536368309:web:33facbccd34c5ec6f192fc',
    messagingSenderId: '772536368309',
    projectId: 'real-estate-app-482d8',
    authDomain: 'real-estate-app-482d8.firebaseapp.com',
    storageBucket: 'real-estate-app-482d8.firebasestorage.app',
    measurementId: 'G-YMRZVTDSYQ',
  );
}
